### ISSUE TITLE
How start demo with JSON Back-End

### ISSUE THREAD

**Issue by dubo** [vitmalina/KickStart#12]
Hi,
  can you update doc, how start demo with new JSON Back-End, I try it under Win8(Firefox/IE) -   with NGINX  or from  fiilesytem , but I unable login to App.

**Comment by dubo** [comment]
I have update my fork forked repo, if my changes are OK for you, I send  I make pull reqest 
There is more problems in Kickstarter project now - missed Json data for admin namespace, bug with master w2ui at ..web/index.html#/home/groups  when  list users is  browsing

**Comment by vitmalina** [comment]
For JSON back-end demo it should be pretty straight forward. You download the repo and then open in your browser /web/index.html. You can go to /web/login.html and typing admin/admin worked for me too. 

The only problem was that I first started, I was in the browser console
```
Failed to load resource: the server responded with a status of 403 (Forbidden)
```
But after setting proper permissions on the files (I use apache on OS X), all was good. I also had to set permissions to /api folder

As for admin pages, they do not work with JSON back-end.

I hope it helps.

**Comment by dubo** [comment]
Thank you for your guidance, I found a hack for Nginx, which solves the problem  with POST:
https://gist.github.com/baskaran-md/e46cc25ccfac83f153bb

**Comment by vitmalina** [comment]
Please resubmit readme file again, I will merge it.
